// demos/next/components/HeroSection.tsx
export default function HeroSection() {
  return (
    <section className="uib-hero">
      <h1>
        Design meets code,
        <br />
        powered by Next.js
      </h1>
      <p>
        A live design bridge that lets you tweak your UI and annotate elements directly in the
        browser — now running on Next.js.
      </p>
      <a href="#" role="button">
        Try it free
      </a>
      <a href="#" role="button" className="secondary">
        Learn more
      </a>
    </section>
  );
}

// demos/nuxt/components/HeroSection.vue
<template>
  <section class="uib-hero">
    <h1>Design meets code,<br />powered by Nuxt</h1>
    <p>
      A live design bridge that lets you tweak your UI and annotate elements directly in the browser
      — now running on Nuxt 3.
    </p>
    <a href="#" role="button">Try it free</a>
    <a href="#" role="button" class="secondary">Learn more</a>
  </section>
</template>
